version: '3.1'
services:
  cart-service:
    image: docker.pkg.github.com/betulcetinkaya/cart-service/${IMAGE_NAME}:${TAG}
    container_name: cart-service
    env_file: docker-compose.env
    ports:
      - 8082:8082
    networks:
        - services
networks:
  services:
    external:
      name: services
